### ISSUE TITLE
Make it work in threads

### ISSUE THREAD

**Issue by bossinc** [hjdarnel/lambdas#3]

**Comment by bossinc** [comment]
I blieve there has been mistake

**Comment by hjdarnel** [comment]
It doesn't show the message as of b710d415933eab26eac717b8e077259e86f3c21b 

🙂

**Comment by hjdarnel** [comment]
Also you can't call Slack slash commands in threads, sry https://twitter.com/SlackHQ/status/1110527621102739456?s=20
