### ISSUE TITLE
I can't use the cats command.

### ISSUE THREAD

**Issue by bossinc** [hjdarnel/lambdas#5]
**Describe the bug**
When I enter command `/printcat` it doesn't print out every cat emoji.

**To Reproduce**
Enter command `/printcat` and see nothing happen. 

**Expected behavior**
Every cat emoji should be printed out.

**Actual behavior**
Nothing happens wtf.

**Additional context**
I think it has something to do with hatred of cats? I'm not sure

**Comment by hjdarnel** [comment]
Thanks for the idea! Let me know if this doesn't match what you think. 😀
